name: SonarCloud Analysis

on:
  push:
    branches:
      - master
jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install SonarScanner for .NET globally
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Add .NET Tools to PATH
        run: |
          echo "$(dotnet tool list -g | grep sonarscanner | awk '{print $4}')" >> $GITHUB_PATH

      - name: SonarCloud - Begin Analysis
        run: dotnet sonarscanner begin /o:"x00218712" /k:"x00218712_testr" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Build project
        run: dotnet build TestRazor.sln

      - name: SonarCloud - End Analysis
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
